services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: skillovate_v2_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - sqlite_data:/app/data

volumes:
  sqlite_data:
