const mongoose = require('mongoose');

const achievementSchema = new mongoose.Schema({
  studentId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User',
    required: true
  },
  collegeId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'College',
    required: true
  },
  type: {
    type: String,
    enum: [
      // Mock Test
      'top_scorer', 'consistent_performer', 'improvement_star', 'fast_solver',
      // Mock Interview
      'excellent_communicator', 'confidence_booster', 'interview_ready',
      // Placement
      'active_applicant', 'shortlisted_candidate', 'placed_candidate', 'dream_offer',
      // Platform Engagement
      'consistent_learner', 'high_performer', 'top_10_ranker'
    ],
    required: true
  },
  title: {
    type: String,
    required: true
  },
  description: String,
  sourceModule: {
    type: String,
    enum: ['test', 'interview', 'placement', 'system'],
    required: true
  },
  referenceId: {
    type: mongoose.Schema.Types.ObjectId
  },
  metricValue: {
    type: Number
  },
  achievedAt: {
    type: Date,
    default: Date.now
  },
  autoGenerated: {
    type: Boolean,
    default: true
  }
}, {
  timestamps: true
});

// Unique constraint: prevent duplicate achievements for same student+type+reference
achievementSchema.index({ studentId: 1, type: 1, referenceId: 1 }, { unique: true, sparse: true });
// For students with system-level achievements (no referenceId), prevent duplicates by type
achievementSchema.index({ studentId: 1, type: 1 }, { unique: false });
achievementSchema.index({ studentId: 1, achievedAt: -1 });
achievementSchema.index({ collegeId: 1, type: 1 });
achievementSchema.index({ type: 1, metricValue: -1 });

module.exports = mongoose.model('Achievement', achievementSchema);
